
version: "3"
services:
  db:
    image: postgres:15.1
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
 
  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
 
  api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/api/uploads
  