version: "3"
services:
  db:
    container_name: jobdeal_db
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - ./jobdeal-api/.env

  pgadmin:
    container_name: jobdeal_db_admin
    image: dpage/pgadmin4:6.18
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - ./jobdeal-api/.env

  api:
    container_name: jobdeal_api
    build:
      context: ./jobdeal-api
    env_file:
      - ./jobdeal-api/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./jobdeal-api/uploads:/api/uploads

  web:
    container_name: jobdeal_web
    build:
      context: ./jobdeal-web
    env_file:
      - ./jobdeal-web/.env
    ports:
      - "3001:3001"
    depends_on:
      - api
