version: "3"
services:
  db:
    container_name: jobdeal_db
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env

  api:
    container_name: jobdeal_api
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/api/uploads
