version: "3"
services:
  db:
    container_name: jobdeal_db
    image: postgres:15.1
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env

  pgadmin:
    container_name: jobdeal_db_admin
    image: dpage/pgadmin4:6.18
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  api:
    container_name: jobdeal_api
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/api/uploads

  frontend:
    container_name: jobdeal_frontend
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - api